spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curriculer?useSSL=false&useTimezone=true&serverTimezone=Europe/Madrid
    username: curriculer
    password: 5V4dWb5y7rUdBwfmpzXBgCvJzMkUrMOK9dDAr5ggrAv3niEW4D
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8888
